runtime: java17
env: standard
# remember to use an instance class compatible with your scaling type
handlers:
  - url: .*
    script: auto
basic_scaling:
  max_instances: 3
  idle_timeout: 10m
service: demokroger

